version: '3.8'

services:
  indexer:
    image: madhesh00/qie-indexer:latest
    container_name: qie-indexer
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    image: madhesh00/qie-frontend:latest
    container_name: qie-frontend
    ports:
      - "5173:80"
    restart: unless-stopped
    depends_on:
      - indexer